using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GXT
{
    // global singleton class for all gxt settings specified in the ini file
    // settings are first generated by the ini file
    // they can be overwritten by command line arguments
    public class gxtSettings
    {
    }
}
